### ISSUE TITLE
-constOffsets comments out one-line code

### ISSUE THREAD

**Issue by colinator27** [WarlockD/GMdsam#3]
If variables and code are declared all on one line, the comments do something like this:
`if(global.debug == 1) if(builtin.room_speed < 40) builtin.room_speed = 200// Constant Offset=0x009EB0EC Size=2 else builtin.room_speed = 30// Constant Offset=0x009EB0FC Size=2;
`
The comments cancel out the rest of the code which is required for the script to run properly. I'd suggest changing it to these kinds of comments:
`var a = 1; /* Comment Here! */ var b = 2;`

**Comment by WarlockD** [comment]
Hah yea I just fixed that, changed it out to blocks.  I have a new release so need try that out with this.

**Comment by WarlockD** [comment]
It looks like it tests right now, but tell me using the new release if you have issues.  fyi I got rid of the -all so just type in "objects" etc.

**Comment by colinator27** [comment]
Oh, sorry I didn't see this lol! I'll try it out now.

**Comment by colinator27** [comment]
It seems to have fixed the issue! :D
